#!/usr/bin/env bash
#  Bash script that stops 4-to_infinity_and_beyond process without kill

pkill -f "4-to_infinity_and_beyond"#!/usr/bin/env bash
#  Bash script that stops 4-to_infinity_and_beyond process without kill

pkill -f "4-to_infinity_and_beyond"
