#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd

while IFS=':' read -r username _ uid _ _ home _
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo
done < "/etc/passwd"
